"""add slug to films_b2c

Revision ID: c9d02294f3fd
Revises: c0de17031e2c
Create Date: 2025-07-27 12:49:14.790930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9d02294f3fd'
down_revision = 'c0de17031e2c'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films_b2c', sa.Column('slug', sa.String(), nullable=False))
    op.create_index(op.f('ix_films_b2c_slug'), 'films_b2c', ['slug'], unique=True)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_films_b2c_slug'), table_name='films_b2c')
    op.drop_column('films_b2c', 'slug')
    # ### end Alembic commands ###
