"""add tmdb_id to Genre

Revision ID: e14f1af20612
Revises: 20250712_094557
Create Date: 2025-07-16 17:44:44.926986

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e14f1af20612'
down_revision = '20250712_094557'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('films_b2c', 'genres')
    op.add_column('genres', sa.Column('tmdb_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'genres', ['tmdb_id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'genres', type_='unique')
    op.drop_column('genres', 'tmdb_id')
    op.add_column('films_b2c', sa.Column('genres', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
