# services/admin_service/Dockerfile
FROM python:3.11-slim

WORKDIR /app

COPY ./app /app/app
COPY alembic /app/alembic
COPY alembic.ini /app/
COPY requirements.txt /app/
COPY entrypoint.sh /entrypoint.sh

RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt \
    && chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
